services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: imomchoudhary/crud-dd-task-mean-app-backend:latest
    # build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_URL=mongodb://mongodb:27017/dd_db
      - PORT=8080
      - CORS_ORIGIN=http://100.49.202.147,http://localhost:80
    depends_on:
      - mongodb

  frontend:
    image: imomchoudhary/crud-dd-task-mean-app-frontend:latest
    # build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data:
